### ISSUE TITLE
Паттерн матчинг на очень большой конструктор 

### ISSUE THREAD

**Issue by olgaklimenko** [paffel2/echobot#1]
Вот такой паттерн матчинг выглядит немного пугающе :),  особенно в основной логике (в функции `echo`).

`(Just message@(TelegramMessage _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ (Just video) _ _ _ _ _ _)) _)`

Предлагаю создать дополнительный тип-сумму:

```
TelegramCommand = Help | Repeat

TgMessage = TextMessage Text | CommandMessage  TelegramCommand | AnimationMessage TelegramAnimation | и тд. 
```
И мапать исходный TelegramMessage в TgMessage и уже его использовать в логике приложения и матчиться на лаконичные конструкторы.

**Comment by paffel2** [comment]
Исправил по этому шаблону, также немного переписал функции для обработки и handle. Переписал пока только для этого исправления. Думаю дальнейшие правки вносить на основании внесенных правок.

**Comment by olgaklimenko** [comment]
Уже смотреть или потом?) Создай пожалуйста пулл реквест, когда пора будет смотреть, так быстрее ревью пойдёт:)

**Comment by paffel2** [comment]
Сделал пул на это исправление
