### ISSUE TITLE
Форматирование кода

### ISSUE THREAD

**Issue by olgaklimenko** [paffel2/echobot#12]
Возможно до исправления всех ишью оно было, но сейчас некоторые файлы уже нуждаются в форматинге. 

Лучше перед каждым коммитом запускать форматирование, или настроить автоматическое форматирование на событие сохранения файла (в vscode) - мы все так делаем :)

**Comment by olgaklimenko** [comment]
У меня больше ишью нет к твоему боту, хорошо выглядит :). Антон потом еще ревью проведет, а я код сервера еще посмотрю.

**Comment by paffel2** [comment]
Хорошо спасибо
