### ISSUE TITLE
Ревью

### ISSUE THREAD

**Issue by goosedb** [paffel2/echobot#17]
```haskell
{-# LANGUAGE OverloadedStrings #-}
...
                C.lookupDefault "" conf (T.pack "bot.type") :: IO String
```

- [x] В этом случае `T.pack` можно опустить
---
```haskell
data Modules
    = BT
    | LG
```
- [x] Вот эта `data` меня тоже малёха смущает, почему реализвал конфиг именно так, а не структурой, в которой есть всё?

Тем более, это просто неудобно. Судя по типу
```haskell
data ConfigModules
    = Bot { ... }
    | Log { ... }

newtype ConfigHandle =
    ConfigHandle
        { getConfig :: Modules -> IO ConfigModules
        }
```

когда ты пихаешь в `getConfig` `BT` тебе так же может прийти с `Log`. 
Мне кажется, это неудачное решение.

---
```haskell
newtype RepeatsNum =
    RepeatsNum
        { repeats_num' :: Int
        }
    deriving (Show, Eq, Generic)
```
- [x] _У нас в кваскеле принято_ `вотТакоеИменование`
Не нужно `JSON` представление переносить на хаскельные имена. В `aeson` есть инструменты, для того, чтобы повставлять подчёркивания между слов в `JSON` представлении, используй их.
- [x]  Имена с `'` тоже лучше не использовать. Если тебе прям необходим этот `newtype` (о чём опять же стоит задуматься, может и не нужен), то обычно принято рекорды `newtype`ов называть с префиксом `get` (`getRepeatsNum`).

---

```haskell
        (RepeatsNum 1)
``` 

- [x] Можно для `RepeatsNum` задерайвить `Num`

---
```haskell
        , ("v", "5.130")
```

- [x] Вот такие вещи можно и нужно уносить в топ-левел константы

---
```haskell 
newtype Ts =
    Ts
        { ts' :: Int
        }
    deriving (Eq, Show, Generic)

newtype Pts =
    Pts
        { pts' :: Int
        }
    deriving (Eq, Show, Generic)
```

- [x] Ваще не понял, че такое `Ts`, че такое `Pts`.  Давай либо названия по-понятнее, либо, если это какой-то термин или че-то такое, то хоть комментик или ссылку на доку контача. 

---
```haskell
            threadDelay 3000000
```

- [x] Опять же конвстанта, 2 раза повторяется.

---

- [x] Я правильно понимаю, что логика самого бота у тебя два раза описана и для телеги и для контача?Как тебе идея фиксировать доменку в одном месте и переиспользовать её в обоих ботах? 

---

```haskell
b1 :: [VkButton]
b1 = [VkButton (VkAction "text" "1" "1")]

b2 :: [VkButton]
b2 = [VkButton (VkAction "text" "2" "2")]

b3 :: [VkButton]
b3 = [VkButton (VkAction "text" "3" "3")]

b4 :: [VkButton]
b4 = [VkButton (VkAction "text" "4" "4")]

b5 :: [VkButton]
b5 = [VkButton (VkAction "text" "5" "5")]

buttonsVk :: [[VkButton]]
buttonsVk = [b1, b2, b3, b4, b5]
```

- [x] Может нагенерить это в пару строк?

---

```haskell
instance FromJSON TelegramMessage where
    parseJSON (Object v) =
        TelegramMessage <$> v .: "message_id" <*> v .:? "from" <*>
        v .:? "sender_chat" <*>
        v .: "date" <*>
        v .: "chat" <*>
        v .:? "forward_from" <*>
        v .:? "forward_from_chat" <*>
        v .:? "forward_from_message_id" <*>
        v .:? "forward_from_signature" <*>
        v .:? "text" <*>
        v .:? "entities" <*>
        v .:? "animation" <*>
        v .:? "caption" <*>
        v .:? "document" <*>
        v .:? "audio" <*>
        v .:? "photo" <*>
        v .:? "video" <*>
        v .:? "sticker" <*>
        v .:? "video_note" <*>
        v .:? "voice" <*>
        v .:? "contact" <*>
        v .:? "location" <*>
        v .:? "venue"
    parseJSON _ = mzero
```
- [x] Вот это тоже `aeson`ом генеретися изично

---
```haskell
            it
                ("Should return new UpdateId and new list of users, because echo function did not receive an update ID, " ++
                 "but get new update, where get new list of users and new UpdateId.")
```
 

- [x] можно использовать многострочные литералы

```haskell
            it "Should return new UpdateId and new list of users, because echo function did not receive an update ID, \
                \but get new update, where get new list of users and new UpdateId."
```
---
```haskell
telegramMessageToTgMessage :: TelegramMessage -> Maybe TgMessage
telegramMessageToTgMessage telegram_message
    | telegramMessageText telegram_message == Just "/repeat" =
        Just $ CommandMessage Repeat
    | telegramMessageText telegram_message == Just "/help" =
        Just $ CommandMessage Help
    | isJust $ telegramMessageText telegram_message =
        TextMessage <$> telegramMessageText telegram_message
...
    | isJust $ telegramMessageVenue telegram_message =
        VenueMessage <$> telegramMessageVenue telegram_message
    | otherwise = Nothing

```

- [x] Вот это функция вообще сомнительная, я её не понимаю. Но `RecordWildCards` уменьшит её примерно в 2 раза. А лучше вообще чо-то с этим сделать, тут зачем-то произведение переводится в сумму. И даже если есть ещё какие-то поля, кроме того, что поймалось первым, оно всё равно не учтётся. Мутно кароче. Объяснишь?)

---

```haskell
buttons :: [[TelegramInlineKeyboardButton]]
buttons = [[TelegramInlineKeyboardButton x x] | x <- ["1", "2", "3", "4", "5"]]
```

- [x] Тоже почему не нагенерировать?

---

```haskell
createParamsAttachment (VkAttachmentDoc _ (VkDoc docId ownerId accessKey)) =
    [("attachment", Just $ T.pack attachStr)]
  where
    attachStr = "doc" ++ show ownerId ++ "_" ++ show docId ++ "_" ++ accessKey
createParamsAttachment (VkAttachmentVideo _ (VkVideo videoId ownerId accessKey)) =
    [("attachment", Just $ T.pack attachStr)]
  where
    attachStr =
        "video" ++ show ownerId ++ "_" ++ show videoId ++ "_" ++ accessKey
```

- [x] Ооочень много прямо одинакового кода

---
```haskell
sendMessageRepeatText hLogger vktoken _ (VkItem _ fromId _ _ _ _ _ (Just button))
```

- [x] `NamedFieldPuns `

**Comment by paffel2** [comment]
1)Можно для RepeatsNum задерайвить Num
А зачем? Это просто упаковка числа. 
2) По поводу логики. В принципе она одинаковая, но из-за специфики апи разная. Потому на мой взгляд не особо выйдет фиксировать домен.
3) По поводу одинакового кода. Да это действительно так, но опять все сводится к именно апи Вконтакте.
4) Для TS и PTS добавил ссылку на апи.
5) 
```haskell
telegramMessageToTgMessage :: TelegramMessage -> Maybe TgMessage
telegramMessageToTgMessage telegram_message
    | telegramMessageText telegram_message == Just "/repeat" =
        Just $ CommandMessage Repeat
    | telegramMessageText telegram_message == Just "/help" =
        Just $ CommandMessage Help
    | isJust $ telegramMessageText telegram_message =
        TextMessage <$> telegramMessageText telegram_message
...
    | isJust $ telegramMessageVenue telegram_message =
        VenueMessage <$> telegramMessageVenue telegram_message
    | otherwise = Nothing
```

Это делалось, избежать длинного паттерн матчинга. Таким образом для каждого вида сообщения, мапается свой тип.
6) В каком плане сгенерить клавиатуру?
