### ISSUE TITLE
Улучшить Readme

### ISSUE THREAD

**Issue by olgaklimenko** [paffel2/echobot#3]
Ридми написано хорошо, есть несколько вещей, которые можно поправить:

- В ридми есть такая строчка, но я не нашла использование бд в проекте:
>> The database name must match the name specified in the file `sql/init_database.sql`

- По ридми не понятно куда надо положить конфиг (надо заглянуть в файл где читаем конфиг, чтобы узнать). Хорошая практика делать директорию для конфига, и создавать там файл с шаблоном конфигурации. Потом достаточно скопировать этот файл и просто подставить свои токены.

**Comment by paffel2** [comment]
Это я копировал readme из сервера, забыл удалить.
