### ISSUE TITLE
Handle pattern

### ISSUE THREAD

**Issue by olgaklimenko** [paffel2/echobot#4]
В коде есть `TelegramHandle`, но он не имеет смысла. Попробуй сделать его полиморфным по монаде (убрать оттуда IO), и написать функцию echo в полиморфной монаде. Потом вызвать echo с `telegramHandler`, где переданы как раз IO функции (API.getMe, API.sendKeyboard и тд).

Потом еще нужно будет написать тесты для функции `echo`, используя моковую монаду вместо m.

(В вк хендлере также нужно сделать)

**Comment by olgaklimenko** [comment]
[Вот тут ](https://www.metalamp.io/articles/service-handle-pattern) наш коллега Олег Ромашин написал статью про использование Хэндл паттерна, можно как раз опираться на неё.

**Comment by paffel2** [comment]
А как тестировать функцию echo если она зациклена. Ее может следует как-то переписать, а уже отдельно создать функцию в которой она будет постоянно перезапускаться?

**Comment by olgaklimenko** [comment]
Для постоянного перезапуска можно попробовать [forever](https://hackage.haskell.org/package/base-4.15.0.0/docs/Control-Monad.html#v:forever) из `startTelegramBot`, но использовать не получится с текущей реализацией, т.к. передается новый список в следующий вызов. Можно запустить общий стейт для всех вызовов `echo` и держать в нём `[(chatId, repeats)]` и обновлять его вместо передачи нового списка вручную.

**Comment by paffel2** [comment]
Ну помимо списка повторов, echo требуется updateId. Почему бы тогда не сделать возвращаемым значением для echo пару из updateId и списка, а потом написать функцию которая будет рекурсивно вызывать echo?

**Comment by olgaklimenko** [comment]
Да, конечно функцию тоже можно написать)
